// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlZEq4VeJvyRmfjMd3pfOIxF0SZVWCyEw',
    appId: '1:163843971251:web:40bfe04eaa2762c15838c6',
    messagingSenderId: '163843971251',
    projectId: 'flutterfirst-5a570',
    authDomain: 'flutterfirst-5a570.firebaseapp.com',
    storageBucket: 'flutterfirst-5a570.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSaCLEjJjoncRrJB9uNZthuNUFBajpc9Q',
    appId: '1:163843971251:android:f53ff6757de8b3595838c6',
    messagingSenderId: '163843971251',
    projectId: 'flutterfirst-5a570',
    storageBucket: 'flutterfirst-5a570.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClE53C-c8yGXIUj22uRCZYRcbMGed8eYk',
    appId: '1:163843971251:ios:35646490911c9db05838c6',
    messagingSenderId: '163843971251',
    projectId: 'flutterfirst-5a570',
    storageBucket: 'flutterfirst-5a570.appspot.com',
    iosClientId: '163843971251-cbgtog99uecgljj1dj3b4oh3n6dedle6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClE53C-c8yGXIUj22uRCZYRcbMGed8eYk',
    appId: '1:163843971251:ios:35646490911c9db05838c6',
    messagingSenderId: '163843971251',
    projectId: 'flutterfirst-5a570',
    storageBucket: 'flutterfirst-5a570.appspot.com',
    iosClientId: '163843971251-cbgtog99uecgljj1dj3b4oh3n6dedle6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirst',
  );
}
